// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/QGL_Graphics.0.h"

WINRT_EXPORT namespace winrt::QGL_Graphics {

struct WINRT_EBO IQGL_GraphicsRT :
    Windows::Foundation::IInspectable,
    impl::consume_t<IQGL_GraphicsRT>
{
    IQGL_GraphicsRT(std::nullptr_t = nullptr) noexcept {}
};

}
