namespace QGL_Projection
{
   [default_interface]
   runtimeclass ContentLoader : Windows.Foundation.IStringable
   {
      ContentLoader(UInt16 val, String name);
      UInt16 Value{ get; };
      String ValueName{ get; };
   }
}