namespace QGL_Projection
{
   [default_interface]
   runtimeclass CompilerVersion : Windows.Foundation.IStringable
   {
      //Constructor.
      CompilerVersion(UInt32 val, String str);

      //Returns the compiler version value.
      UInt32 Value { get; };

      static CompilerVersion Version_0_1 { get; };

      static CompilerVersion Version_0_2 { get; };

      static CompilerVersion VersionLatest{ get; };
      
      static Windows.Foundation.Collections.IVector<CompilerVersion> 
         CompilerVersions{ get; };
   }
}