import "projections\ContentMetadata.idl";
import "projections\ContentProjectEntry.idl";

namespace QGL_Projection
{
   [default_interface]
   runtimeclass ContentProject : Windows.UI.Xaml.Data.INotifyPropertyChanged
   {
      ContentProject();

      Boolean LoadFromFileAsync(Windows.Storage.StorageFile f);

      Boolean SaveProjectFile(Windows.Storage.StorageFile f);

      QGL_Projection.ContentMetadata Metadata;
   
      Windows.Foundation.Collections.IObservableVector<IInspectable> Entries;
   }
}