namespace QGL_Projection
{
   [default_interface]
   runtimeclass ContentLoader : Windows.Foundation.IStringable
   {
      //Constructor
      ContentLoader(UInt16 enumValue, String name);

      //Content loader ID value.
      //This maps to C++ enum qgl::content::CONTENT_LOADER_ID
      UInt16 Value{ get; };
   }
}