import "projections\ContentLoader.idl";
import "projections\ResourceType.idl";
import "projections\CompilerVersion.idl";

namespace QGL_Projection
{
   [default_interface]
   runtimeclass ContentMetadata : Windows.UI.Xaml.Data.INotifyPropertyChanged
   {
      ContentMetadata();

      Boolean ContentVisible;
      Boolean ContentObeyPhysics;
      String ContentName;
      UInt16 ResourceType;
      UInt16 ContentLoader;
      UInt32 CompilerVersion;

      GUID Guid();
   }
}