// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/base.h"


static_assert(winrt::check_version(CPPWINRT_VERSION, "1.0.180821.2"), "Mismatched component and base headers.");
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.Foundation.Collections.h"
#include "winrt/impl/QGL_Graphics.2.h"

namespace winrt::impl {

template <typename D>
struct produce<D, QGL_Graphics::IQGL_GraphicsRT> : produce_base<D, QGL_Graphics::IQGL_GraphicsRT>
{};

}

WINRT_EXPORT namespace winrt::QGL_Graphics {

inline QGL_GraphicsRT::QGL_GraphicsRT() :
    QGL_GraphicsRT(impl::call_factory<QGL_GraphicsRT>([](auto&& f) { return f.template ActivateInstance<QGL_GraphicsRT>(); }))
{}

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::experimental::reflect {

}

WINRT_EXPORT namespace std {

template<> struct hash<winrt::QGL_Graphics::IQGL_GraphicsRT> : winrt::impl::hash_base<winrt::QGL_Graphics::IQGL_GraphicsRT> {};
template<> struct hash<winrt::QGL_Graphics::QGL_GraphicsRT> : winrt::impl::hash_base<winrt::QGL_Graphics::QGL_GraphicsRT> {};

}
