// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/base.h"


static_assert(winrt::check_version(CPPWINRT_VERSION, "1.0.180821.2"), "Mismatched component and base headers.");
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.Foundation.Collections.h"
#include "winrt/impl/QGL_Content.2.h"

namespace winrt::impl {

template <typename D>
struct produce<D, QGL_Content::IQGL_ContentRT> : produce_base<D, QGL_Content::IQGL_ContentRT>
{};

}

WINRT_EXPORT namespace winrt::QGL_Content {

inline QGL_ContentRT::QGL_ContentRT() :
    QGL_ContentRT(impl::call_factory<QGL_ContentRT>([](auto&& f) { return f.template ActivateInstance<QGL_ContentRT>(); }))
{}

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::experimental::reflect {

}

WINRT_EXPORT namespace std {

template<> struct hash<winrt::QGL_Content::IQGL_ContentRT> : winrt::impl::hash_base<winrt::QGL_Content::IQGL_ContentRT> {};
template<> struct hash<winrt::QGL_Content::QGL_ContentRT> : winrt::impl::hash_base<winrt::QGL_Content::QGL_ContentRT> {};

}
