// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/Windows.UI.Xaml.Interop.1.h"
#include "winrt/impl/QGL_Content_Builder.Helpers.1.h"

WINRT_EXPORT namespace winrt::QGL_Content_Builder::Helpers {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::QGL_Content_Builder::Helpers {

struct WINRT_EBO InverseBoolConverter :
    Windows::UI::Xaml::Data::IValueConverter
{
    InverseBoolConverter(std::nullptr_t) noexcept {}
    InverseBoolConverter();
};

}
