// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/QGL_Content.1.h"

WINRT_EXPORT namespace winrt::QGL_Content {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::QGL_Content {

struct WINRT_EBO QGL_ContentRT :
    QGL_Content::IQGL_ContentRT
{
    QGL_ContentRT(std::nullptr_t) noexcept {}
    QGL_ContentRT();
};

}
