// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/QGL_Projection.1.h"
#include "winrt/impl/Windows.Storage.1.h"
#include "winrt/impl/Windows.UI.Xaml.Data.1.h"
#include "winrt/impl/QGL_Content_Builder.Extensions.1.h"

WINRT_EXPORT namespace winrt::QGL_Content_Builder::Extensions {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::QGL_Content_Builder::Extensions {

struct WINRT_EBO ExtensionProvider :
    QGL_Content_Builder::Extensions::IExtensionProvider,
    impl::require<ExtensionProvider, Windows::UI::Xaml::Data::INotifyPropertyChanged>
{
    ExtensionProvider(std::nullptr_t) noexcept {}
    ExtensionProvider();
};

struct WINRT_EBO UnknownContentExtension :
    QGL_Content_Builder::Extensions::IUnknownContentExtension,
    impl::require<UnknownContentExtension, QGL_Projection::IContentExtension>
{
    UnknownContentExtension(std::nullptr_t) noexcept {}
    UnknownContentExtension();
};

}
