// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/QGL_Projection.0.h"
#include "winrt/impl/Windows.Storage.0.h"
#include "winrt/impl/Windows.UI.Xaml.Data.0.h"
#include "winrt/impl/QGL_Content_Builder.Extensions.0.h"

WINRT_EXPORT namespace winrt::QGL_Content_Builder::Extensions {

struct WINRT_EBO IExtensionProvider :
    Windows::Foundation::IInspectable,
    impl::consume_t<IExtensionProvider>
{
    IExtensionProvider(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IUnknownContentExtension :
    Windows::Foundation::IInspectable,
    impl::consume_t<IUnknownContentExtension>
{
    IUnknownContentExtension(std::nullptr_t = nullptr) noexcept {}
};

}
