// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/QGL_Model.0.h"

WINRT_EXPORT namespace winrt::QGL_Model {

struct WINRT_EBO IQGL_ModelRT :
    Windows::Foundation::IInspectable,
    impl::consume_t<IQGL_ModelRT>
{
    IQGL_ModelRT(std::nullptr_t = nullptr) noexcept {}
};

}
