// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/QGL_Model.1.h"

WINRT_EXPORT namespace winrt::QGL_Model {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::QGL_Model {

struct WINRT_EBO QGL_ModelRT :
    QGL_Model::IQGL_ModelRT
{
    QGL_ModelRT(std::nullptr_t) noexcept {}
    QGL_ModelRT();
};

}
