// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

WINRT_EXPORT namespace winrt::QGL_Content_Builder::Extensions {

struct ExtensionProvider;

}

WINRT_EXPORT namespace winrt::QGL_Projection {

struct ContentInfo;

}

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Data {

struct PropertyChangedEventHandler;

}

WINRT_EXPORT namespace winrt::QGL_Content_Builder::PageModels {

struct IHomePageVM;
struct IHomePageVMFactory;
struct IRecentProjectVM;
struct IRecentProjectVMFactory;
struct HomePageVM;
struct RecentProjectVM;

}

namespace winrt::impl {

template <> struct category<QGL_Content_Builder::PageModels::IHomePageVM>{ using type = interface_category; };
template <> struct category<QGL_Content_Builder::PageModels::IHomePageVMFactory>{ using type = interface_category; };
template <> struct category<QGL_Content_Builder::PageModels::IRecentProjectVM>{ using type = interface_category; };
template <> struct category<QGL_Content_Builder::PageModels::IRecentProjectVMFactory>{ using type = interface_category; };
template <> struct category<QGL_Content_Builder::PageModels::HomePageVM>{ using type = class_category; };
template <> struct category<QGL_Content_Builder::PageModels::RecentProjectVM>{ using type = class_category; };
template <> struct name<QGL_Content_Builder::PageModels::IHomePageVM>{ static constexpr auto & value{ L"QGL_Content_Builder.PageModels.IHomePageVM" }; };
template <> struct name<QGL_Content_Builder::PageModels::IHomePageVMFactory>{ static constexpr auto & value{ L"QGL_Content_Builder.PageModels.IHomePageVMFactory" }; };
template <> struct name<QGL_Content_Builder::PageModels::IRecentProjectVM>{ static constexpr auto & value{ L"QGL_Content_Builder.PageModels.IRecentProjectVM" }; };
template <> struct name<QGL_Content_Builder::PageModels::IRecentProjectVMFactory>{ static constexpr auto & value{ L"QGL_Content_Builder.PageModels.IRecentProjectVMFactory" }; };
template <> struct name<QGL_Content_Builder::PageModels::HomePageVM>{ static constexpr auto & value{ L"QGL_Content_Builder.PageModels.HomePageVM" }; };
template <> struct name<QGL_Content_Builder::PageModels::RecentProjectVM>{ static constexpr auto & value{ L"QGL_Content_Builder.PageModels.RecentProjectVM" }; };
template <> struct guid_storage<QGL_Content_Builder::PageModels::IHomePageVM>{ static constexpr guid value{ 0x656D15F3,0xA216,0x571F,{ 0x99,0x4D,0x86,0xC0,0x2C,0x3E,0x89,0x57 } }; };
template <> struct guid_storage<QGL_Content_Builder::PageModels::IHomePageVMFactory>{ static constexpr guid value{ 0xB1AADBB8,0xC0B2,0x5BBC,{ 0x85,0x91,0x0A,0x4F,0x5A,0xE3,0xF2,0x23 } }; };
template <> struct guid_storage<QGL_Content_Builder::PageModels::IRecentProjectVM>{ static constexpr guid value{ 0x6DBA2C70,0x88F0,0x5AB0,{ 0x96,0x4A,0xB0,0x5B,0x98,0x91,0x76,0x5F } }; };
template <> struct guid_storage<QGL_Content_Builder::PageModels::IRecentProjectVMFactory>{ static constexpr guid value{ 0xB9962E5C,0x8B5A,0x584E,{ 0x84,0x49,0xFF,0xAD,0xC0,0x5E,0xCB,0xC2 } }; };
template <> struct default_interface<QGL_Content_Builder::PageModels::HomePageVM>{ using type = QGL_Content_Builder::PageModels::IHomePageVM; };
template <> struct default_interface<QGL_Content_Builder::PageModels::RecentProjectVM>{ using type = QGL_Content_Builder::PageModels::IRecentProjectVM; };

template <> struct abi<QGL_Content_Builder::PageModels::IHomePageVM>{ struct type : IInspectable
{
    virtual int32_t WINRT_CALL get_IsProjectLoading(bool* value) noexcept = 0;
    virtual int32_t WINRT_CALL get_IsProjectSaving(bool* value) noexcept = 0;
    virtual int32_t WINRT_CALL get_RecentFiles(void** value) noexcept = 0;
    virtual int32_t WINRT_CALL ClearRecentFiles() noexcept = 0;
    virtual int32_t WINRT_CALL PopulateRecentFiles(void** operation) noexcept = 0;
};};

template <> struct abi<QGL_Content_Builder::PageModels::IHomePageVMFactory>{ struct type : IInspectable
{
    virtual int32_t WINRT_CALL CreateInstance(void* extensionProvider, void** value) noexcept = 0;
};};

template <> struct abi<QGL_Content_Builder::PageModels::IRecentProjectVM>{ struct type : IInspectable
{
    virtual int32_t WINRT_CALL get_ContentName(void** value) noexcept = 0;
    virtual int32_t WINRT_CALL get_Path(void** value) noexcept = 0;
};};

template <> struct abi<QGL_Content_Builder::PageModels::IRecentProjectVMFactory>{ struct type : IInspectable
{
    virtual int32_t WINRT_CALL CreateInstance(void* filePath, void* info, void** value) noexcept = 0;
};};

template <typename D>
struct consume_QGL_Content_Builder_PageModels_IHomePageVM
{
    bool IsProjectLoading() const;
    bool IsProjectSaving() const;
    Windows::Foundation::Collections::IObservableVector<Windows::Foundation::IInspectable> RecentFiles() const;
    void ClearRecentFiles() const;
    Windows::Foundation::IAsyncAction PopulateRecentFiles() const;
};
template <> struct consume<QGL_Content_Builder::PageModels::IHomePageVM> { template <typename D> using type = consume_QGL_Content_Builder_PageModels_IHomePageVM<D>; };

template <typename D>
struct consume_QGL_Content_Builder_PageModels_IHomePageVMFactory
{
    QGL_Content_Builder::PageModels::HomePageVM CreateInstance(QGL_Content_Builder::Extensions::ExtensionProvider const& extensionProvider) const;
};
template <> struct consume<QGL_Content_Builder::PageModels::IHomePageVMFactory> { template <typename D> using type = consume_QGL_Content_Builder_PageModels_IHomePageVMFactory<D>; };

template <typename D>
struct consume_QGL_Content_Builder_PageModels_IRecentProjectVM
{
    hstring ContentName() const;
    hstring Path() const;
};
template <> struct consume<QGL_Content_Builder::PageModels::IRecentProjectVM> { template <typename D> using type = consume_QGL_Content_Builder_PageModels_IRecentProjectVM<D>; };

template <typename D>
struct consume_QGL_Content_Builder_PageModels_IRecentProjectVMFactory
{
    QGL_Content_Builder::PageModels::RecentProjectVM CreateInstance(param::hstring const& filePath, QGL_Projection::ContentInfo const& info) const;
};
template <> struct consume<QGL_Content_Builder::PageModels::IRecentProjectVMFactory> { template <typename D> using type = consume_QGL_Content_Builder_PageModels_IRecentProjectVMFactory<D>; };

}
