// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/Windows.Storage.1.h"
#include "winrt/impl/Windows.Storage.Streams.1.h"
#include "winrt/impl/Windows.UI.Xaml.Data.1.h"
#include "winrt/impl/Windows.UI.Xaml.Interop.1.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.1.h"
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/QGL_Projection.1.h"

WINRT_EXPORT namespace winrt::QGL_Projection {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::QGL_Projection {

struct WINRT_EBO CompilerVersion :
    QGL_Projection::ICompilerVersion,
    impl::require<CompilerVersion, Windows::Foundation::IStringable>
{
    CompilerVersion(std::nullptr_t) noexcept {}
    CompilerVersion(uint32_t val);
    static QGL_Projection::CompilerVersion Version_0_1();
    static QGL_Projection::CompilerVersion Version_0_2();
    static Windows::Foundation::Collections::IVector<QGL_Projection::CompilerVersion> CompilerVersions();
    static Windows::Foundation::Collections::IObservableVector<Windows::Foundation::IInspectable> ObservableCompilerVersions();
};

struct WINRT_EBO ContentInfo :
    QGL_Projection::IContentInfo,
    impl::require<ContentInfo, Windows::UI::Xaml::Data::INotifyPropertyChanged>
{
    ContentInfo(std::nullptr_t) noexcept {}
    ContentInfo();
    static void WriteContentInfoToBuffer(QGL_Projection::ContentInfo const& info, Windows::Storage::Streams::DataWriter const& r);
    static QGL_Projection::ContentInfo ReadContentInfoFromBuffer(Windows::Storage::Streams::DataReader const& r, param::vector<QGL_Projection::ResourceType> const& supportedResourceTypes);
};

struct WINRT_EBO ContentLoader :
    QGL_Projection::IContentLoader,
    impl::require<ContentLoader, Windows::Foundation::IStringable>
{
    ContentLoader(std::nullptr_t) noexcept {}
    ContentLoader(uint16_t val, param::hstring const& name);
};

struct WINRT_EBO ContentProject :
    QGL_Projection::IContentProject,
    impl::require<ContentProject, Windows::UI::Xaml::Data::INotifyPropertyChanged>
{
    ContentProject(std::nullptr_t) noexcept {}
    ContentProject();
};

struct WINRT_EBO ContentProjectEntry :
    QGL_Projection::IContentProjectEntry,
    impl::require<ContentProjectEntry, Windows::Foundation::IStringable, Windows::UI::Xaml::Data::INotifyPropertyChanged>
{
    ContentProjectEntry(std::nullptr_t) noexcept {}
    ContentProjectEntry(param::hstring const& filePath, QGL_Projection::ContentInfo const& info);
};

struct WINRT_EBO ResourceType :
    QGL_Projection::IResourceType,
    impl::require<ResourceType, Windows::Foundation::IStringable>
{
    ResourceType(std::nullptr_t) noexcept {}
    ResourceType(uint16_t val, param::hstring const& name, array_view<QGL_Projection::ContentLoader const> loaders);
};

struct WINRT_EBO XamlMetaDataProvider :
    Windows::UI::Xaml::Markup::IXamlMetadataProvider
{
    XamlMetaDataProvider(std::nullptr_t) noexcept {}
    XamlMetaDataProvider();
};

}
