// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/QGL_Graphics.1.h"

WINRT_EXPORT namespace winrt::QGL_Graphics {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::QGL_Graphics {

struct WINRT_EBO QGL_GraphicsRT :
    QGL_Graphics::IQGL_GraphicsRT
{
    QGL_GraphicsRT(std::nullptr_t) noexcept {}
    QGL_GraphicsRT();
};

}
