#pragma once
#include "include/qgl_content_include.h"

namespace qgl::content
{
   static constexpr uint64_t QGL_CONTENT_PROJECT_MAGIC_NUMBER =
      0x8A473F4DB11D8CE7;

   static constexpr uint64_t QGL_CONTENT_PROJECT_ENTRY_SEPERATOR_MAGIC_NUMBER =
      0xF6C3A57BD87C798B;

   enum RESOURCE_TYPES : uint16_t
   {
      RESOURCE_TYPE_UNKNOWN = 0,

      //Basic Type Related
      RESOURCE_TYPE_STRING = 1,
      RESOURCE_TYPE_INTEGER = 2,
      RESOURCE_TYPE_FLOAT = 3,

      //Graphics Types
      RESOURCE_TYPE_GEOMETRY,
      RESOURCE_TYPE_TEXTURE,
      RESOURCE_TYPE_SHADER,
      RESOURCE_TYPE_DESCRIPTION,

      RESOURCE_TYPE_LIGHT,
      RESOURCE_TYPE_CAMERA,
      RESOURCE_TYPE_BRUSH,
      RESOURCE_TYPE_TEXT_FORMAT,

      //Physics Types


      //Sound Types

      //AI Types


      //Other Types
   };

   enum CONTENT_LOADER_IDS : uint16_t
   {
      CONTENT_LOADER_ID_UNKNOWN = 0,

      //Basic Types
      CONTENT_LOADER_ID_STRING = 1,
      CONTENT_LOADER_ID_WSTRING = 2,

      CONTENT_LOADER_ID_INT8,
      CONTENT_LOADER_ID_INT16,
      CONTENT_LOADER_ID_INT32,
      CONTENT_LOADER_ID_INT64,

      CONTENT_LOADER_ID_UINT8,
      CONTENT_LOADER_ID_UINT16,
      CONTENT_LOADER_ID_UINT32,
      CONTENT_LOADER_ID_UINT64,

      //CONTENT_LOADER_ID_FLOAT32,
      //CONTENT_LOADER_ID_FLOAT64,

      //CONTENT_LOADER_ID_FLOAT2,
      //CONTENT_LOADER_ID_FLOAT3,
      //CONTENT_LOADER_ID_FLOAT4,
      //CONTENT_LOADER_ID_FLOAT2_LIST,
      //CONTENT_LOADER_ID_FLOAT3_LIST,
      //CONTENT_LOADER_ID_FLOAT4_LIST,


      //Graphics Types
      CONTENT_LOADER_ID_DDS,
      //CONTENT_LOADER_ID_OBJ,
      //CONTENT_LOADER_ID_FBX,
      CONTENT_LOADER_ID_LIGHT,
      CONTENT_LOADER_ID_CAMERA,
      CONTENT_LOADER_ID_WTEXT,
      CONTENT_LOADER_ID_DEPTH_STENCIL,
      CONTENT_LOADER_ID_TEXT_FORMAT,
      CONTENT_LOADER_ID_BRUSH,
      CONTENT_LOADER_ID_SAMPLER,

      CONTENT_LOADER_ID_SHADER_SOURCE,
      CONTENT_LOADER_ID_SHADER_COMPILED,

      //Physics Types
      //CONTENT_LOADER_ID_AABB,
      //CONTENT_LOADER_ID_SPHERE,

      //Sound Types

      //AI Types

      //Other Types
      CONTENT_LOADER_ID_GRAPHICS_CONFIG,
      CONTENT_LOADER_ID_STORE_CONFIG,
   };
}