// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/QGL_Content.h"

namespace winrt::QGL_Content::implementation {

template <typename D, typename... I>
struct WINRT_EBO QGL_ContentRT_base : implements<D, QGL_Content::IQGL_ContentRT, I...>
{
    using base_type = QGL_ContentRT_base;
    using class_type = QGL_Content::QGL_ContentRT;
    using implements_type = typename QGL_ContentRT_base::implements_type;
    using implements_type::implements_type;
    
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"QGL_Content.QGL_ContentRT";
    }
};

}

namespace winrt::QGL_Content::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO QGL_ContentRTT : implements<D, Windows::Foundation::IActivationFactory, I...>
{
    using instance_type = QGL_Content::QGL_ContentRT;

    hstring GetRuntimeClassName() const
    {
        return L"QGL_Content.QGL_ContentRT";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_QGL_CONTENTRT_XAML_G_H) || __has_include("QGL_ContentRT.xaml.g.h")

#include "QGL_ContentRT.xaml.g.h"

#else

namespace winrt::QGL_Content::implementation
{
    template <typename D, typename... I>
    using QGL_ContentRTT = QGL_ContentRT_base<D, I...>;
}

#endif
