// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/QGL_Model.h"

namespace winrt::QGL_Model::implementation {

template <typename D, typename... I>
struct WINRT_EBO QGL_ModelRT_base : implements<D, QGL_Model::IQGL_ModelRT, I...>
{
    using base_type = QGL_ModelRT_base;
    using class_type = QGL_Model::QGL_ModelRT;
    using implements_type = typename QGL_ModelRT_base::implements_type;
    using implements_type::implements_type;
    
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"QGL_Model.QGL_ModelRT";
    }
};

}

namespace winrt::QGL_Model::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO QGL_ModelRTT : implements<D, Windows::Foundation::IActivationFactory, I...>
{
    using instance_type = QGL_Model::QGL_ModelRT;

    hstring GetRuntimeClassName() const
    {
        return L"QGL_Model.QGL_ModelRT";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_QGL_MODELRT_XAML_G_H) || __has_include("QGL_ModelRT.xaml.g.h")

#include "QGL_ModelRT.xaml.g.h"

#else

namespace winrt::QGL_Model::implementation
{
    template <typename D, typename... I>
    using QGL_ModelRTT = QGL_ModelRT_base<D, I...>;
}

#endif
