namespace QGL_Content_Builder.Extensions
{
   [default_interface]
   runtimeclass ExtensionProvider : Windows.UI.Xaml.Data.INotifyPropertyChanged
   {
      ExtensionProvider();
      Boolean CheckSupport(QGL_Projection.ContentInfo info);
      String GetExtensionForLoader(QGL_Projection.ContentInfo info);

      Windows.Foundation.Collections.IObservableVector<IInspectable> Extensions{ get; };
      Windows.Foundation.Collections.IObservableVector<IInspectable> ObservableResourceTypes { get; };
   }
}