// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/Windows.Storage.0.h"
#include "winrt/impl/Windows.Storage.Streams.0.h"
#include "winrt/impl/Windows.UI.Xaml.Data.0.h"
#include "winrt/impl/Windows.UI.Xaml.Interop.0.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.0.h"
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/QGL_Projection.0.h"

WINRT_EXPORT namespace winrt::QGL_Projection {

struct WINRT_EBO ICompilerVersion :
    Windows::Foundation::IInspectable,
    impl::consume_t<ICompilerVersion>
{
    ICompilerVersion(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ICompilerVersionFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ICompilerVersionFactory>
{
    ICompilerVersionFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ICompilerVersionStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ICompilerVersionStatics>
{
    ICompilerVersionStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IContentExtension :
    Windows::Foundation::IInspectable,
    impl::consume_t<IContentExtension>
{
    IContentExtension(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IContentInfo :
    Windows::Foundation::IInspectable,
    impl::consume_t<IContentInfo>
{
    IContentInfo(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IContentInfoStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IContentInfoStatics>
{
    IContentInfoStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IContentLoader :
    Windows::Foundation::IInspectable,
    impl::consume_t<IContentLoader>
{
    IContentLoader(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IContentLoaderFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IContentLoaderFactory>
{
    IContentLoaderFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IContentProject :
    Windows::Foundation::IInspectable,
    impl::consume_t<IContentProject>
{
    IContentProject(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IContentProjectEntry :
    Windows::Foundation::IInspectable,
    impl::consume_t<IContentProjectEntry>
{
    IContentProjectEntry(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IContentProjectEntryFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IContentProjectEntryFactory>
{
    IContentProjectEntryFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IResourceType :
    Windows::Foundation::IInspectable,
    impl::consume_t<IResourceType>
{
    IResourceType(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IResourceTypeFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IResourceTypeFactory>
{
    IResourceTypeFactory(std::nullptr_t = nullptr) noexcept {}
};

}
