// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/QGL_Content_Builder.Extensions.0.h"
#include "winrt/impl/QGL_Projection.0.h"
#include "winrt/impl/Windows.UI.Xaml.Data.0.h"
#include "winrt/impl/QGL_Content_Builder.PageModels.0.h"

WINRT_EXPORT namespace winrt::QGL_Content_Builder::PageModels {

struct WINRT_EBO IHomePageVM :
    Windows::Foundation::IInspectable,
    impl::consume_t<IHomePageVM>
{
    IHomePageVM(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IHomePageVMFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IHomePageVMFactory>
{
    IHomePageVMFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRecentProjectVM :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRecentProjectVM>
{
    IRecentProjectVM(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRecentProjectVMFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRecentProjectVMFactory>
{
    IRecentProjectVMFactory(std::nullptr_t = nullptr) noexcept {}
};

}
