// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Interop {

struct TypeName;

}

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Data {

struct IValueConverter;

}

WINRT_EXPORT namespace winrt::QGL_Content_Builder::Helpers {

struct InverseBoolConverter;

}

namespace winrt::impl {

template <> struct category<QGL_Content_Builder::Helpers::InverseBoolConverter>{ using type = class_category; };
template <> struct name<QGL_Content_Builder::Helpers::InverseBoolConverter>{ static constexpr auto & value{ L"QGL_Content_Builder.Helpers.InverseBoolConverter" }; };
template <> struct default_interface<QGL_Content_Builder::Helpers::InverseBoolConverter>{ using type = Windows::UI::Xaml::Data::IValueConverter; };

}
