// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/Windows.UI.Xaml.Interop.0.h"
#include "winrt/impl/QGL_Content_Builder.Helpers.0.h"

WINRT_EXPORT namespace winrt::QGL_Content_Builder::Helpers {

}
