// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/QGL_Content_Builder.Extensions.1.h"
#include "winrt/impl/QGL_Projection.1.h"
#include "winrt/impl/Windows.UI.Xaml.Data.1.h"
#include "winrt/impl/QGL_Content_Builder.PageModels.1.h"

WINRT_EXPORT namespace winrt::QGL_Content_Builder::PageModels {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::QGL_Content_Builder::PageModels {

struct WINRT_EBO HomePageVM :
    QGL_Content_Builder::PageModels::IHomePageVM,
    impl::require<HomePageVM, Windows::UI::Xaml::Data::INotifyPropertyChanged>
{
    HomePageVM(std::nullptr_t) noexcept {}
    HomePageVM(QGL_Content_Builder::Extensions::ExtensionProvider const& extensionProvider);
};

struct WINRT_EBO RecentProjectVM :
    QGL_Content_Builder::PageModels::IRecentProjectVM,
    impl::require<RecentProjectVM, Windows::UI::Xaml::Data::INotifyPropertyChanged>
{
    RecentProjectVM(std::nullptr_t) noexcept {}
    RecentProjectVM(param::hstring const& filePath, QGL_Projection::ContentInfo const& info);
};

}
