namespace qgl.graphics
{
   [default_interface]
   runtimeclass window_rt
   {
      window_rt(Windows.UI.Core.CoreWindow wnd,
               Windows.UI.ViewManagement.ApplicationView appView);

   }
}