import "Extensions\ExtensionProvider.idl";

namespace QGL_Content_Builder.PageModels
{
   [default_interface]
   runtimeclass HomePageVM : Windows.UI.Xaml.Data.INotifyPropertyChanged
   {
      HomePageVM(QGL_Content_Builder.Extensions.ExtensionProvider extensionProvider);

      Boolean IsProjectLoading{ get; };
      Boolean IsProjectSaving{ get; };
      Windows.Foundation.Collections.IObservableVector<IInspectable> RecentFiles{ get; };

      void ClearRecentFiles();
      Windows.Foundation.IAsyncAction PopulateRecentFiles();
   }
}