namespace QGL_Content_Builder.PageModels
{
   [default_interface]
   runtimeclass RecentProjectVM : Windows.UI.Xaml.Data.INotifyPropertyChanged
   {
      RecentProjectVM(String filePath,
                      QGL_Projection.ContentInfo info);

      String ContentName{ get; };
      String Path{ get; };
   }
}