import "ContentInfo\ResourceType.idl";
import "ContentInfo\ContentLoader.idl";
import "ContentProject\ContentProjectEntry.idl";

namespace QGL_Projection
{
   [default_interface]
   runtimeclass ContentProject : Windows.UI.Xaml.Data.INotifyPropertyChanged
   {
      ContentProject();
      ContentInfo ContentInfo;
      Windows.Foundation.Collections.IObservableVector<IInspectable> ObservableEntries;

      Windows.Foundation.IAsyncOperation<Boolean> LoadFromFileAsync(Windows.Storage.StorageFile f,
                                                        Windows.Foundation.Collections.IVector<ResourceType> supported);
      Windows.Foundation.IAsyncOperation<Boolean> SaveToFileAsync(Windows.Storage.StorageFile f);

   }
}