namespace QGL_Projection
{
   [default_interface]
   runtimeclass CompilerVersion : Windows.Foundation.IStringable
   {
      CompilerVersion(UInt32 val);
      UInt32 Value { get; };
      String ValueName{ get; };

      static CompilerVersion Version_0_1{ get; };
      static CompilerVersion Version_0_2{ get; };
      static Windows.Foundation.Collections.IVector<CompilerVersion> CompilerVersions{ get; };
      static Windows.Foundation.Collections.IObservableVector<IInspectable> ObservableCompilerVersions{ get; };
   }
}