namespace QGL_Projection
{
   interface IContentExtension
   {
      UInt16 ResourceType { get; };
      UInt16 ContentLoaderID{ get; };
      String ContentExtension{ get; };
      String ContentLoaderName{ get; };
      String ResourceTypeName{ get; };

      Windows.Foundation.IAsyncAction Open(Windows.Storage.StorageFile f);
      Windows.Foundation.IAsyncAction Save(Windows.Storage.StorageFile f);
   }
}