// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/Windows.UI.Xaml.Interop.h"
#include "winrt/QGL_Content_Builder.Helpers.h"

namespace winrt::QGL_Content_Builder::Helpers::implementation {

template <typename D, typename... I>
struct WINRT_EBO InverseBoolConverter_base : implements<D, Windows::UI::Xaml::Data::IValueConverter, I...>
{
    using base_type = InverseBoolConverter_base;
    using class_type = QGL_Content_Builder::Helpers::InverseBoolConverter;
    using implements_type = typename InverseBoolConverter_base::implements_type;
    using implements_type::implements_type;
    
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"QGL_Content_Builder.Helpers.InverseBoolConverter";
    }
};

}

namespace winrt::QGL_Content_Builder::Helpers::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO InverseBoolConverterT : implements<D, Windows::Foundation::IActivationFactory, I...>
{
    using instance_type = QGL_Content_Builder::Helpers::InverseBoolConverter;

    hstring GetRuntimeClassName() const
    {
        return L"QGL_Content_Builder.Helpers.InverseBoolConverter";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_INVERSEBOOLCONVERTER_XAML_G_H) || __has_include("Helpers.InverseBoolConverter.xaml.g.h")

#include "Helpers.InverseBoolConverter.xaml.g.h"

#else

namespace winrt::QGL_Content_Builder::Helpers::implementation
{
    template <typename D, typename... I>
    using InverseBoolConverterT = InverseBoolConverter_base<D, I...>;
}

#endif
