// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/QGL_Content.0.h"

WINRT_EXPORT namespace winrt::QGL_Content {

struct WINRT_EBO IQGL_ContentRT :
    Windows::Foundation::IInspectable,
    impl::consume_t<IQGL_ContentRT>
{
    IQGL_ContentRT(std::nullptr_t = nullptr) noexcept {}
};

}
