// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/Windows.Storage.h"
#include "winrt/Windows.Storage.Streams.h"
#include "winrt/Windows.UI.Xaml.Data.h"
#include "winrt/Windows.Foundation.h"
#include "winrt/QGL_Projection.h"

namespace winrt::QGL_Projection::implementation {

template <typename D, typename... I>
struct WINRT_EBO CompilerVersion_base : implements<D, QGL_Projection::ICompilerVersion, Windows::Foundation::IStringable, I...>
{
    using base_type = CompilerVersion_base;
    using class_type = QGL_Projection::CompilerVersion;
    using implements_type = typename CompilerVersion_base::implements_type;
    using implements_type::implements_type;
    
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"QGL_Projection.CompilerVersion";
    }
};

}

namespace winrt::QGL_Projection::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO CompilerVersionT : implements<D, Windows::Foundation::IActivationFactory, QGL_Projection::ICompilerVersionFactory, QGL_Projection::ICompilerVersionStatics, I...>
{
    using instance_type = QGL_Projection::CompilerVersion;

    hstring GetRuntimeClassName() const
    {
        return L"QGL_Projection.CompilerVersion";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        throw hresult_not_implemented();
    }

    QGL_Projection::CompilerVersion CreateInstance(uint32_t val)
    {
        return make<T>(val);
    }

    QGL_Projection::CompilerVersion Version_0_1()
    {
        return T::Version_0_1();
    }

    QGL_Projection::CompilerVersion Version_0_2()
    {
        return T::Version_0_2();
    }

    Windows::Foundation::Collections::IVector<QGL_Projection::CompilerVersion> CompilerVersions()
    {
        return T::CompilerVersions();
    }

    Windows::Foundation::Collections::IObservableVector<Windows::Foundation::IInspectable> ObservableCompilerVersions()
    {
        return T::ObservableCompilerVersions();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_COMPILERVERSION_XAML_G_H) || __has_include("CompilerVersion.xaml.g.h")

#include "CompilerVersion.xaml.g.h"

#else

namespace winrt::QGL_Projection::implementation
{
    template <typename D, typename... I>
    using CompilerVersionT = CompilerVersion_base<D, I...>;
}

#endif
