// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/Windows.Storage.h"
#include "winrt/Windows.Storage.Streams.h"
#include "winrt/Windows.UI.Xaml.Data.h"
#include "winrt/Windows.Foundation.h"
#include "winrt/QGL_Projection.h"

namespace winrt::QGL_Projection::implementation {

template <typename D, typename... I>
struct WINRT_EBO ContentProjectEntry_base : implements<D, QGL_Projection::IContentProjectEntry, Windows::Foundation::IStringable, Windows::UI::Xaml::Data::INotifyPropertyChanged, I...>
{
    using base_type = ContentProjectEntry_base;
    using class_type = QGL_Projection::ContentProjectEntry;
    using implements_type = typename ContentProjectEntry_base::implements_type;
    using implements_type::implements_type;
    
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"QGL_Projection.ContentProjectEntry";
    }
};

}

namespace winrt::QGL_Projection::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO ContentProjectEntryT : implements<D, Windows::Foundation::IActivationFactory, QGL_Projection::IContentProjectEntryFactory, I...>
{
    using instance_type = QGL_Projection::ContentProjectEntry;

    hstring GetRuntimeClassName() const
    {
        return L"QGL_Projection.ContentProjectEntry";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        throw hresult_not_implemented();
    }

    QGL_Projection::ContentProjectEntry CreateInstance(hstring const& filePath, QGL_Projection::ContentInfo const& info)
    {
        return make<T>(filePath, info);
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_CONTENTPROJECTENTRY_XAML_G_H) || __has_include("ContentProjectEntry.xaml.g.h")

#include "ContentProjectEntry.xaml.g.h"

#else

namespace winrt::QGL_Projection::implementation
{
    template <typename D, typename... I>
    using ContentProjectEntryT = ContentProjectEntry_base<D, I...>;
}

#endif
