// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/Windows.Storage.h"
#include "winrt/Windows.Storage.Streams.h"
#include "winrt/Windows.UI.Xaml.Data.h"
#include "winrt/Windows.Foundation.h"
#include "winrt/QGL_Projection.h"

namespace winrt::QGL_Projection::implementation {

template <typename D, typename... I>
struct WINRT_EBO ContentInfo_base : implements<D, QGL_Projection::IContentInfo, Windows::UI::Xaml::Data::INotifyPropertyChanged, I...>
{
    using base_type = ContentInfo_base;
    using class_type = QGL_Projection::ContentInfo;
    using implements_type = typename ContentInfo_base::implements_type;
    using implements_type::implements_type;
    
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"QGL_Projection.ContentInfo";
    }
};

}

namespace winrt::QGL_Projection::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO ContentInfoT : implements<D, Windows::Foundation::IActivationFactory, QGL_Projection::IContentInfoStatics, I...>
{
    using instance_type = QGL_Projection::ContentInfo;

    hstring GetRuntimeClassName() const
    {
        return L"QGL_Projection.ContentInfo";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }

    void WriteContentInfoToBuffer(QGL_Projection::ContentInfo const& info, Windows::Storage::Streams::DataWriter const& r)
    {
        T::WriteContentInfoToBuffer(info, r);
    }

    QGL_Projection::ContentInfo ReadContentInfoFromBuffer(Windows::Storage::Streams::DataReader const& r, Windows::Foundation::Collections::IVector<QGL_Projection::ResourceType> const& supportedResourceTypes)
    {
        return T::ReadContentInfoFromBuffer(r, supportedResourceTypes);
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_CONTENTINFO_XAML_G_H) || __has_include("ContentInfo.xaml.g.h")

#include "ContentInfo.xaml.g.h"

#else

namespace winrt::QGL_Projection::implementation
{
    template <typename D, typename... I>
    using ContentInfoT = ContentInfo_base<D, I...>;
}

#endif
