// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/Windows.Storage.h"
#include "winrt/Windows.Storage.Streams.h"
#include "winrt/Windows.UI.Xaml.Data.h"
#include "winrt/Windows.Foundation.h"
#include "winrt/QGL_Projection.h"

namespace winrt::QGL_Projection::implementation {

template <typename D, typename... I>
struct WINRT_EBO ContentProject_base : implements<D, QGL_Projection::IContentProject, Windows::UI::Xaml::Data::INotifyPropertyChanged, I...>
{
    using base_type = ContentProject_base;
    using class_type = QGL_Projection::ContentProject;
    using implements_type = typename ContentProject_base::implements_type;
    using implements_type::implements_type;
    
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"QGL_Projection.ContentProject";
    }
};

}

namespace winrt::QGL_Projection::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO ContentProjectT : implements<D, Windows::Foundation::IActivationFactory, I...>
{
    using instance_type = QGL_Projection::ContentProject;

    hstring GetRuntimeClassName() const
    {
        return L"QGL_Projection.ContentProject";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_CONTENTPROJECT_XAML_G_H) || __has_include("ContentProject.xaml.g.h")

#include "ContentProject.xaml.g.h"

#else

namespace winrt::QGL_Projection::implementation
{
    template <typename D, typename... I>
    using ContentProjectT = ContentProject_base<D, I...>;
}

#endif
