// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/base.h"


static_assert(winrt::check_version(CPPWINRT_VERSION, "1.0.180821.2"), "Mismatched component and base headers.");
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.Foundation.Collections.h"
#include "winrt/impl/QGL_Model.2.h"

namespace winrt::impl {

template <typename D>
struct produce<D, QGL_Model::IQGL_ModelRT> : produce_base<D, QGL_Model::IQGL_ModelRT>
{};

}

WINRT_EXPORT namespace winrt::QGL_Model {

inline QGL_ModelRT::QGL_ModelRT() :
    QGL_ModelRT(impl::call_factory<QGL_ModelRT>([](auto&& f) { return f.template ActivateInstance<QGL_ModelRT>(); }))
{}

}

WINRT_EXPORT namespace std {

template<> struct hash<winrt::QGL_Model::IQGL_ModelRT> : winrt::impl::hash_base<winrt::QGL_Model::IQGL_ModelRT> {};
template<> struct hash<winrt::QGL_Model::QGL_ModelRT> : winrt::impl::hash_base<winrt::QGL_Model::QGL_ModelRT> {};

}
