// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/base.h"


static_assert(winrt::check_version(CPPWINRT_VERSION, "1.0.180821.2"), "Mismatched component and base headers.");
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.Foundation.Collections.h"
#include "winrt/impl/Windows.UI.Xaml.Interop.2.h"
#include "winrt/impl/QGL_Content_Builder.Helpers.2.h"
#include "winrt/QGL_Content_Builder.h"

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::QGL_Content_Builder::Helpers {

inline InverseBoolConverter::InverseBoolConverter() :
    InverseBoolConverter(impl::call_factory<InverseBoolConverter>([](auto&& f) { return f.template ActivateInstance<InverseBoolConverter>(); }))
{}

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::experimental::reflect {

}

WINRT_EXPORT namespace std {

template<> struct hash<winrt::QGL_Content_Builder::Helpers::InverseBoolConverter> : winrt::impl::hash_base<winrt::QGL_Content_Builder::Helpers::InverseBoolConverter> {};

}
