// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#include "pch.h"
#include "MainPage.h"
#include "XamlMetaDataProvider.h"
#include "Extensions.ExtensionProvider.h"
#include "Extensions.UnknownContentExtension.h"
#include "Helpers.InverseBoolConverter.h"
#include "PageModels.HomePageVM.h"
#include "PageModels.RecentProjectVM.h"

int32_t WINRT_CALL WINRT_CanUnloadNow() noexcept
{
#ifdef _WRL_MODULE_H_
    if (!::Microsoft::WRL::Module<::Microsoft::WRL::InProc>::GetModule().Terminate())
    {
        return 1; // S_FALSE
    }
#endif

    if (winrt::get_module_lock())
    {
        return 1; // S_FALSE
    }

    winrt::clear_factory_cache();
    return 0; // S_OK
}

int32_t WINRT_CALL WINRT_GetActivationFactory(void* classId, void** factory) noexcept
{
    try
    {
        *factory = nullptr;
        uint32_t length{};
        wchar_t const* const buffer = WINRT_WindowsGetStringRawBuffer(classId, &length);
        std::wstring_view const name{ buffer, length };

        auto requal = [](std::wstring_view const& left, std::wstring_view const& right) noexcept
        {
            return std::equal(left.rbegin(), left.rend(), right.rbegin(), right.rend());
        };

        if (requal(name, L"QGL_Content_Builder.MainPage"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::QGL_Content_Builder::factory_implementation::MainPage>());
            return 0;
        }

        if (requal(name, L"QGL_Content_Builder.XamlMetaDataProvider"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::QGL_Content_Builder::factory_implementation::XamlMetaDataProvider>());
            return 0;
        }

        if (requal(name, L"QGL_Content_Builder.Extensions.ExtensionProvider"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::QGL_Content_Builder::Extensions::factory_implementation::ExtensionProvider>());
            return 0;
        }

        if (requal(name, L"QGL_Content_Builder.Extensions.UnknownContentExtension"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::QGL_Content_Builder::Extensions::factory_implementation::UnknownContentExtension>());
            return 0;
        }

        if (requal(name, L"QGL_Content_Builder.Helpers.InverseBoolConverter"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::QGL_Content_Builder::Helpers::factory_implementation::InverseBoolConverter>());
            return 0;
        }

        if (requal(name, L"QGL_Content_Builder.PageModels.HomePageVM"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::QGL_Content_Builder::PageModels::factory_implementation::HomePageVM>());
            return 0;
        }

        if (requal(name, L"QGL_Content_Builder.PageModels.RecentProjectVM"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::QGL_Content_Builder::PageModels::factory_implementation::RecentProjectVM>());
            return 0;
        }

#ifdef _WRL_MODULE_H_
        return ::Microsoft::WRL::Module<::Microsoft::WRL::InProc>::GetModule().GetActivationFactory(static_cast<HSTRING>(classId), reinterpret_cast<::IActivationFactory**>(factory));
#else
        return winrt::hresult_class_not_available(name).to_abi();
#endif
    }
    catch (...) { return winrt::to_hresult(); }
}
